apiVersion: certmerge.lecentre.net/v1alpha1
kind: CertMerge
metadata:
  name: "test-certmerge-labels"
spec:
  selector:
    - labelselector:
        matchExpressions:
        - key: certmerge
          operator: exists
      namespace: default
  name: test-cert-labels
  namespace: default