apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certmerges.certmerge.lecentre.net
spec:
  group: certmerge.lecentre.net
  names:
    kind: CertMerge
    listKind: CertMergeList
    plural: certmerges
    singular: certmerge
  scope: Namespaced
  version: v1alpha1
